### ISSUE TITLE
Add license to text and code

### ISSUE THREAD

**Issue by bast** [neicnordic/neic.no#13]
I recommend to license the website code under MPL v2.0 and to license the text under CC-BY v4.0.

**Comment by yohell** [comment]
I trust your judgement when it comes to licensing.

**Comment by bast** [comment]
OK I will add this. Is there any material as of now that we are not allowed to license?

**Comment by yohell** [comment]
Idk? Photos?

⁣Sent from TypeApp ​

**Comment by bast** [comment]
OK so I will state we license everything except the photos.
